repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: Check if files are black-formatted (no updates)
        args: [--check]
-   repo: https://github.com/per11235813/psje-precommit-hooks
    rev: v0.0.5
    hooks:
    -   id: check-notebook
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--check-only]
      name: isort (python)